name: Build test Docker image

on:
  push:
    branches: ["table2asn-testing-script"]
  pull_request:
    branches: [ "table2asn-testing-script"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile -t seqsender:latest
        docker run -t -d seqsender:latest --name seqsender
        docker exec -it seqsender bash seqsender-kickoff --help
