name: Build test Docker image

on:
  push:
    branches: [ "master" , "dockerfile-fix"]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile -t seqsender
        docker images
        docker image inspect
        docker run -rm seqsender echo test
