name: Build test Docker image

on:
  push:
    branches: [ "master" , "dockerfile-fix"]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      with:
        context:  .
        load: true
        cache-from: type=gha
        cache-to: type=gha, mode=max
      run: |
        docker build . --file Dockerfile -t seqsender:latest
        docker images
        docker exec -it seqsender bash seqsender-kickoff --help
